void qalloc_undo(int32_t _Lsize_0);
void _Ncp1_Pdecl_import_4(_Ncp1_Ninclude _Lpath_0, uint32_t _Lrow_1, uint32_t _Lcol_2, bool _Lrequire_3);
void _Ncp1_Pdecl_template_inst_3(_Ncp1_Nid _Lname_0, uint32_t _Lrow_1, uint32_t _Lcol_2);
void _Ncp1_Pdecl_template_code_4(_Ncp1_Nid _Lname_0, uint32_t _Lrow_1, bool _Lwith_reflection_2, bool _Lno_cache_3);
void _Ncp1_Pdecl_func_begin_3(_Ncp1_Nid _Lname_0, uint32_t _Lrow_1, uint32_t _Lcol_2);
void _Ncp1_Pdecl_func_end_2(uint32_t _Lrow_0, uint32_t _Lcol_1);
void _Ncp1_Pdecl_struct_end_2(uint32_t _Lrow_0, uint32_t _Lcol_1);
void _Ncp1_Pdecl_var_begin_3(_Ncp1_Nid _Lname_0, uint32_t _Lrow_1, uint32_t _Lcol_2);
void _Ncp1_Pdecl_var_attr_real_name_1(_Ncp1_Nid _Lname_0);
void _Ncp1_Pdecl_var_attr_extern_0();
void _Ncp1_Pdecl_var_attr_no_decl_0();
void _Ncp1_Pdecl_var_end_0();
void _Ncp1_Pdecl_var_as_farg_2(uint32_t _Lrow_0, uint32_t _Lcol_1);
void _Ncp1_Pfarg_next_group_0();
void _Ncp1_Pdecl_var_as_this_0();
void _Ncp1_Pdecl_var_as_fvar_0();
void _Ncp1_Pfunc_body_end_0();
void _Ncp1_Pfunc_header_end_0();
void _Ncp1_Pexpr_push_call_2(uint32_t _Lrow_0, uint32_t _Lcol_1);
_Ncp1_Nexpr_i _Ncp1_Pexpr_pop_func_2(_Ncp1_Nat _Lat_0, _Ncp1_Nid _Lfunc_name_1);
_Ncp1_Nexpr_i _Ncp1_Pexpr_pop_metafunc_2(_Ncp1_Nat _Lat_0, _Ncp1_Nid _Lfunc_name_1);
_Ncp1_Nexpr_i _Ncp1_Pexpr_pop_metamethod_2(_Ncp1_Nexpr_i _Lthiss_0, _Ncp1_Nid _Lfunc_name_1);
_Ncp1_Nexpr_i _Ncp1_Pexpr_pop_method_2(_Ncp1_Nexpr_i _Lthiss_0, _Ncp1_Nid _Lfunc_name_1);
void _Ncp1_Pmetacarg_push_1(_Ncp1_Nexpr_i _Lexpr_0);
void _Ncp1_Pmetacarg_next_group_0();
void _Ncp1_Pcarg_push_1(_Ncp1_Nexpr_i _Lexpr_0);
void _Ncp1_Pcarg_push_str_1(_Ncp1_Nexpr_i _Lexpr_0);
void _Ncp1_Pcarg_next_group_0();
void _Ncp1_Pexpr2stmt_5(_Ncp1_Nexpr_i _Le_idx_0, uint32_t _Lbegin_row_1, uint32_t _Lbegin_col_2, uint32_t _Lend_row_3, uint32_t _Lend_col_4);
void _Ncp1_Pstmt_return_5(_Ncp1_Nexpr_i _Le_0, uint32_t _Lbegin_row_1, uint32_t _Lbegin_col_2, uint32_t _Lend_row_3, uint32_t _Lend_col_4);
void _Ncp1_Pstmt_continue_5(_Ncp1_Nid _Lid_0, uint32_t _Lbegin_row_1, uint32_t _Lbegin_col_2, uint32_t _Lend_row_3, uint32_t _Lend_col_4);
void _Ncp1_Pstmt_break_5(_Ncp1_Nid _Lid_0, uint32_t _Lbegin_row_1, uint32_t _Lbegin_col_2, uint32_t _Lend_row_3, uint32_t _Lend_col_4);
void _Ncp1_Pfunc_attr_main_0();
void _Ncp1_Pfunc_attr_decl_0();
void _Ncp1_Pfunc_attr_cp1_name_0();
void _Ncp1_Pfunc_attr_process_0();
void _Ncp1_Pfunc_attr_inline_0();
void _Ncp1_Pfunc_attr_var_args_0();
void _Ncp1_Pfunc_attr_no_decl_0();
void _Ncp1_Pfunc_attr_no_body_0();
void _Ncp1_Pfunc_attr_overload_get_0();
void _Ncp1_Pfunc_attr_overload_set_0();
void _Ncp1_Pfunc_attr_overload_math_0();
void _Ncp1_Pfunc_attr_overload_bools_0();
void _Ncp1_Pfunc_attr_overload_compare_0();
void _Ncp1_Pfunc_attr_overload_if_begin_0();
void _Ncp1_Pfunc_attr_overload_if_else_0();
void _Ncp1_Pfunc_attr_overload_if_end_0();
void _Ncp1_Pfunc_attr_overload_statement_0();
void _Ncp1_Pfunc_attr_real_name_1(_Ncp1_Nid _Lname_0);
void _Ncp1_Pfunc_attr_meta_method_3(_Ncp1_Nid _Lprefix1_0, _Ncp1_Nid _Lprefix2_1, _Ncp1_Nid _Lend_2);
void _Ncp1_Pfunc_attr_case_1(_Ncp1_Nid _Lname_0);
void _Ncp1_Penum_attr_soa_field_2(_Ncp1_Nat _Lat_0, _Ncp1_Nid _Lid_1);
void _Ncp1_Penum_attr_no_decl_0();
void _Ncp1_Penum_attr_real_name_1(_Ncp1_Nid _Lid_0);
_Ncp1_Nexpr_i _Ncp1_Pexpr_lvar_4(_Ncp1_Nid _Lname_0, uint8_t _Ldecl_1, uint32_t _Lrow_2, uint32_t _Lcol_3);
_Ncp1_Nexpr_i _Ncp1_Pexpr_gvar_4(_Ncp1_Nat _Lat_0, _Ncp1_Nid _Lname_1, uint32_t _Lrow_2, uint32_t _Lcol_3);
_Ncp1_Nexpr_i _Ncp1_Pexpr_fvar_4(_Ncp1_Nexpr_i _Lexpr_0, _Ncp1_Nid _Lmember_1, uint32_t _Lrow_2, uint32_t _Lcol_3);
_Ncp1_Nexpr_i _Ncp1_Pexpr_soa_field_5(_Ncp1_Nexpr_i _Lexpr_0, _Ncp1_Nid _Lgroup_1, _Ncp1_Nid _Lfield_2, uint32_t _Lrow_3, uint32_t _Lcol_4);
_Ncp1_Nexpr_i _Ncp1_Pexpr_assign_3(_Ncp1_Nexpr_i _Lleft_0, _Ncp1_Nexpr_i _Lright_1, _Ncp1_Nassign _Ltype_2);
_Ncp1_Nexpr_i _Ncp1_Pexpr_math_3(_Ncp1_Nexpr_i _Lleft_0, _Ncp1_Nexpr_i _Lright_1, _Ncp1_Nmath _Ltype_2);
_Ncp1_Nexpr_i _Ncp1_Pexpr_math_add_2(_Ncp1_Nexpr_i _Lexpr_0, _Ncp1_Nexpr_i _Lright_1);
_Ncp1_Nexpr_i _Ncp1_Pexpr_bools_3(_Ncp1_Nexpr_i _Lleft_0, _Ncp1_Nexpr_i _Lright_1, _Ncp1_Nbools _Ltype_2);
_Ncp1_Nexpr_i _Ncp1_Pexpr_bools_add_2(_Ncp1_Nexpr_i _Lbools_0, _Ncp1_Nexpr_i _Lright_1);
char* _Ncp1_Ptoken_name_1(_Ncp1_Ntoken _Ltok_0);
void _Ncp1_Pdecl_var_type_1(_Ncp1_Nat _Ltype_0);
void _Ncp1_Pdecl_var_this_0();
void _Ncp1_Pstmt_lvar_add_4(_Ncp1_Nid _Lname_0, _Ncp1_Nexpr_i _Lset_1, uint32_t _Lrow_2, uint32_t _Lcol_3);
void _Ncp1_Pstmt_lvar_end_2(uint32_t _Lend_row_0, uint32_t _Lend_col_1);
void _Ncp1_Pdecl_include_begin_3(_Ncp1_Ninclude _Linc_0, uint32_t _Lrow_1, uint32_t _Lcol_2);
void _Ncp1_Pdecl_include_end_0();
void _Ncp1_Pdecl_at_basic_1(_Ncp1_Nbasic_type_id _Ltype_0);
void _Ncp1_Pdecl_at_add_4(_Ncp1_Nid _Lname_0, _Ncp1_Nname_type _Ltype_1, uint32_t _Lrow_2, uint32_t _Lcol_3);
void _Ncp1_Pdecl_at_begin_2(uint32_t _Lrow_0, uint32_t _Lcol_1);
void _Ncp1_Pdecl_at_begin_struct_3(_Ncp1_Nid _Lname_0, uint32_t _Lrow_1, uint32_t _Lcol_2);
void _Ncp1_Pdecl_at_end_0();
void _Ncp1_Pdecl_alias_4(_Ncp1_Nid _Lname_0, _Ncp1_Nat _Lat_1, uint32_t _Lrow_2, uint32_t _Lcol_3);
void _Ncp1_Pat_push_4(_Ncp1_Nid _Lname_0, _Ncp1_Nname_type _Ltype_1, uint32_t _Lrow_2, uint32_t _Lcol_3);
_Ncp1_Nat _Ncp1_Pat_done_0();
void _Ncp1_Pat_begin_0();
void _Ncp1_Pat_begin_relative_0();
void _Ncp1_Pat_begin_relative_pause_0();
void _Ncp1_Pat_begin_relative_resume_0();
void _Ncp1_Pat_root_0();
void _Ncp1_Pat_alias_3(_Ncp1_Nid _Lname_0, uint32_t _Lrow_1, uint32_t _Lcol_2);
void _Ncp1_Pat_graves_3(int8_t _Lgraves_0, uint32_t _Lrow_1, uint32_t _Lcol_2);
_Ncp1_Nat _Ncp1_Pat_basic_type_1(_Ncp1_Nbasic_type_id _Ltype_0);
void _Ncp1_Pdecl_var_as_gvar_0();
void _Ncp1_Ptype_info_arr_2(_Ncp1_Nexpr_i* _Lexpr_v_0, uint8_t _Lexpr_c_1);
void _Ncp1_Ptype_info_ref_1(int8_t _Lc_0);
void _Ncp1_Ptype_info_static_0();
void _Ncp1_Ptype_info_begin_1(bool _Lconst_0);
void _Ncp1_Ptype_info_finalize_0();
_Ncp1_Nexpr_i _Ncp1_Pexpr_int_2(int32_t _Lvalue_0, _Ncp1_Nexpr_int _Ltype_1);
_Ncp1_Nexpr_i _Ncp1_Pexpr_int64_2(int64_t _Lvalue_0, _Ncp1_Nexpr_int _Ltype_1);
_Ncp1_Nexpr_i _Ncp1_Pexpr_f32_1(float _Lvalue_0);
_Ncp1_Nexpr_i _Ncp1_Pexpr_f64_1(double _Lvalue_0);
_Ncp1_Nexpr_i _Ncp1_Pexpr_size_of_type_1(_Ncp1_Nat _Lat_0);
_Ncp1_Nexpr_i _Ncp1_Pexpr_null_0();
void _Ncp1_Pdecl_at_begin_enum_3(_Ncp1_Nid _Lname_0, uint32_t _Lrow_1, uint32_t _Lcol_2);
void _Ncp1_Pdecl_enum_end_3(_Ncp1_Nat _Lbase_type_0, uint32_t _Lrow_1, uint32_t _Lcol_2);
_Ncp1_Nexpr_i _Ncp1_Pexpr_cvar_2(_Ncp1_Nat _Lat_0, _Ncp1_Nid _Lname_1);
void _Ncp1_Penum_add_cvar_3(_Ncp1_Nid _Lname_0, uint32_t _Lrow_1, uint32_t _Lcol_2);
void _Ncp1_Pdecl_add_cvar_3(_Ncp1_Nid _Lname_0, uint32_t _Lrow_1, uint32_t _Lcol_2);
void _Ncp1_Penum_set_cvar_expr_1(_Ncp1_Nexpr_i _Lset_0);
void _Ncp1_Pstruct_attr_real_name_1(_Ncp1_Nid _Lname_0);
void _Ncp1_Pstruct_attr_aligned_1(uint32_t _Laligned_0);
void _Ncp1_Pstruct_attr_union_0();
void _Ncp1_Pstruct_attr_no_decl_0();
_Ncp1_Nexpr_i _Ncp1_Pexpr_str_2(_Ncp1_Nexpr_i _Lprev_0, bool _Lmacro_1);
_Ncp1_Nexpr_i _Ncp1_Pexpr_unary_2(_Ncp1_Nexpr_i _Lexpr_0, _Ncp1_Nunary _Ltype_1);
_Ncp1_Nexpr_i _Ncp1_Pexpr_ref_1(_Ncp1_Nexpr_i _Lexpr_0);
_Ncp1_Nexpr_i _Ncp1_Pexpr_cast_fast_2(_Ncp1_Nexpr_i _Lexpr_0, _Ncp1_Nat _Ltype_1);
_Ncp1_Nexpr_i _Ncp1_Pexpr_index_3(_Ncp1_Nexpr_i _Lleft_0, _Ncp1_Nexpr_i* _Lright_v_1, int32_t _Lright_c_2);
void _Ncp1_Penum_base_begin_0();
void _Ncp1_Pstmt_switch_begin_0();
void _Ncp1_Pstmt_switch_set_6(_Ncp1_Nexpr_i _Lexpr_0, uint32_t _Lbegin_row_1, uint32_t _Lbegin_col_2, uint32_t _Lend_row_3, uint32_t _Lend_col_4, _Ncp1_Nexpr_i _Lcases_5);
void _Ncp1_Pstmt_switch_expr_add_1(_Ncp1_Nexpr_i _Lexpr_0);
void _Ncp1_Pstmt_switch_case_begin_5(uint32_t _Lbegin_row_0, uint32_t _Lbegin_col_1, uint32_t _Lend_row_2, uint32_t _Lend_col_3, bool _Lfall_through_4);
void _Ncp1_Pstmt_switch_case_end_0();
void _Ncp1_Pstmt_switch_default_begin_5(uint32_t _Lbegin_row_0, uint32_t _Lbegin_col_1, uint32_t _Lend_row_2, uint32_t _Lend_col_3, bool _Lfall_through_4);
void _Ncp1_Pstmt_switch_default_end_0();
void _Ncp1_Pstmt_switch_end_0();
void _Ncp1_Pstmt_if_begin_0();
void _Ncp1_Pstmt_if_set_5(_Ncp1_Nexpr_i _Lexpr_0, uint32_t _Lbegin_row_1, uint32_t _Lbegin_col_2, uint32_t _Lend_row_3, uint32_t _Lend_col_4);
void _Ncp1_Pstmt_if_end_0();
void _Ncp1_Pstmt_loop_begin_0();
void _Ncp1_Pstmt_loop_set_6(_Ncp1_Nexpr_i _Lexpr_0, uint32_t _Lbegin_row_1, uint32_t _Lbegin_col_2, uint32_t _Lend_row_3, uint32_t _Lend_col_4, struct _Ncp1_Nstmt_space* _Lcontinu_5);
void _Ncp1_Pstmt_loop_end_0();
void _Ncp1_Pstmt_elif_begin_0();
void _Ncp1_Pstmt_elif_set_5(_Ncp1_Nexpr_i _Lexpr_0, uint32_t _Lbegin_row_1, uint32_t _Lbegin_col_2, uint32_t _Lend_row_3, uint32_t _Lend_col_4);
void _Ncp1_Pstmt_elif_end_0();
void _Ncp1_Pstmt_else_set_0();
void _Ncp1_Pstmt_else_end_0();
void _Ncp1_Pstmt_if_end_ifs_0();
struct _Ncp1_Nstmt_space* _Ncp1_Pstmt_space_begin_0();
struct _Ncp1_Nstmt_space* _Ncp1_Pstmt_space_begin_detach_0();
struct _Ncp1_Nstmt_space* _Ncp1_Pstmt_space_end_0();
_Ncp1_Nexpr_i _Ncp1_Pexpr_compare_3(_Ncp1_Nexpr_i _Lleft_0, _Ncp1_Nexpr_i _Lright_1, _Ncp1_Ncompare _Ltype_2);
_Ncp1_Nexpr_i _Ncp1_Pexpr_bool_1(bool _Lvalue_0);
_Ncp1_Nexpr_i _Ncp1_Pexpr_char_1(int32_t _Lvalue_0);
void _Ncp1_Pcvar_attr_real_name_1(_Ncp1_Nid _Lname_0);
void _Ncp1_Pcvar_attr_no_decl_0();
void _Ncp1_Pcvar_attr_no_name_0();
void _Ncp1_Pcvar_attr_dont_count_0();
