void qalloc_undo(int32_t _Lsize_0);
void _Nglc_Pdecl_func_begin_3(_Nglc_Nid _Lname_0, int32_t _Lrow_1, int32_t _Lcol_2);
void _Nglc_Pdecl_func_end_2(int32_t _Lrow_0, int32_t _Lcol_1);
void _Nglc_Pdecl_struct_end_2(int32_t _Lrow_0, int32_t _Lcol_1);
void _Nglc_Pdecl_var_begin_3(_Nglc_Nid _Lname_0, int32_t _Lrow_1, int32_t _Lcol_2);
void _Nglc_Pdecl_var_attr_real_name_1(_Nglc_Nid _Lname_0);
void _Nglc_Pdecl_var_attr_extern_0();
void _Nglc_Pdecl_var_attr_no_decl_0();
void _Nglc_Pdecl_var_end_0();
void _Nglc_Pdecl_var_as_farg_2(int32_t _Lrow_0, int32_t _Lcol_1);
void _Nglc_Pfarg_next_group_0();
void _Nglc_Pdecl_var_as_this_0();
void _Nglc_Pdecl_var_as_fvar_0();
void _Nglc_Pfunc_body_end_0();
void _Nglc_Pexpr_push_call_2(int32_t _Lrow_0, int32_t _Lcol_1);
_Nglc_Nexpr_i _Nglc_Pexpr_pop_func_2(_Nglc_Nat _Lat_0, _Nglc_Nid _Lfunc_name_1);
_Nglc_Nexpr_i _Nglc_Pexpr_pop_method_2(_Nglc_Nexpr_i _Lthis_0, _Nglc_Nid _Lfunc_name_1);
void _Nglc_Pcarg_push_1(_Nglc_Nexpr_i _Lexpr_0);
void _Nglc_Pcarg_push_str_1(_Nglc_Nexpr_i _Lexpr_0);
void _Nglc_Pcarg_next_group_0();
void _Nglc_Pexpr2stmt_5(_Nglc_Nexpr_i _Le_0, int32_t _Lbegin_row_1, int32_t _Lbegin_col_2, int32_t _Lend_row_3, int32_t _Lend_col_4);
void _Nglc_Pstmt_return_5(_Nglc_Nexpr_i _Le_0, int32_t _Lbegin_row_1, int32_t _Lbegin_col_2, int32_t _Lend_row_3, int32_t _Lend_col_4);
void _Nglc_Pstmt_continue_5(_Nglc_Nid _Lid_0, int32_t _Lbegin_row_1, int32_t _Lbegin_col_2, int32_t _Lend_row_3, int32_t _Lend_col_4);
void _Nglc_Pstmt_break_5(_Nglc_Nid _Lid_0, int32_t _Lbegin_row_1, int32_t _Lbegin_col_2, int32_t _Lend_row_3, int32_t _Lend_col_4);
void _Nglc_Pfunc_attr_main_0();
void _Nglc_Pfunc_attr_decl_0();
void _Nglc_Pfunc_attr_cgl_name_0();
void _Nglc_Pfunc_attr_process_0();
void _Nglc_Pfunc_attr_inline_0();
void _Nglc_Pfunc_attr_var_args_0();
void _Nglc_Pfunc_attr_no_decl_0();
void _Nglc_Pfunc_attr_no_body_0();
void _Nglc_Pfunc_attr_real_name_1(_Nglc_Nid _Lname_0);
void _Nglc_Pfunc_attr_case_1(_Nglc_Nid _Lname_0);
_Nglc_Nexpr_i _Nglc_Pexpr_lvar_4(_Nglc_Nid _Lname_0, uint8_t _Ldecl_1, int32_t _Lrow_2, int32_t _Lcol_3);
_Nglc_Nexpr_i _Nglc_Pexpr_gvar_2(_Nglc_Nat _Lat_0, _Nglc_Nid _Lname_1);
_Nglc_Nexpr_i _Nglc_Pexpr_fvar_2(_Nglc_Nexpr_i _Lexpr_0, _Nglc_Nid _Lmember_1);
_Nglc_Nexpr_i _Nglc_Pexpr_assign_3(_Nglc_Nexpr_i _Lleft_0, _Nglc_Nexpr_i _Lright_1, _Nglc_Nassign _Ltype_2);
_Nglc_Nexpr_i _Nglc_Pexpr_math_3(_Nglc_Nexpr_i _Lleft_0, _Nglc_Nexpr_i _Lright_1, _Nglc_Nmath _Ltype_2);
_Nglc_Nexpr_i _Nglc_Pexpr_math_add_2(_Nglc_Nexpr_i _Lexpr_0, _Nglc_Nexpr_i _Lright_1);
_Nglc_Nexpr_i _Nglc_Pexpr_bools_3(_Nglc_Nexpr_i _Lleft_0, _Nglc_Nexpr_i _Lright_1, _Nglc_Nbools _Ltype_2);
_Nglc_Nexpr_i _Nglc_Pexpr_bools_add_2(_Nglc_Nexpr_i _Lbools_0, _Nglc_Nexpr_i _Lright_1);
char* _Nglc_Ptoken_name_1(_Nglc_Ntoken _Ltok_0);
void _Nglc_Pdecl_var_type_1(_Nglc_Nat _Ltype_0);
void _Nglc_Pdecl_var_this_0();
void _Nglc_Pstmt_lvar_add_4(_Nglc_Nid _Lname_0, _Nglc_Nexpr_i _Lset_1, int32_t _Lrow_2, int32_t _Lcol_3);
void _Nglc_Pstmt_lvar_end_2(int32_t _Lend_row_0, int32_t _Lend_col_1);
void _Nglc_Pdecl_include_begin_3(_Nglc_Ninclude _Linc_0, int32_t _Lrow_1, int32_t _Lcol_2);
void _Nglc_Pdecl_include_end_0();
void _Nglc_Pdecl_at_basic_1(_Nglc_Nbasic_type_id _Ltype_0);
void _Nglc_Pdecl_at_add_2(_Nglc_Nid _Lname_0, _Nglc_Nname_type _Ltype_1);
void _Nglc_Pdecl_at_begin_2(int32_t _Lrow_0, int32_t _Lcol_1);
void _Nglc_Pdecl_at_begin_struct_3(_Nglc_Nid _Lname_0, int32_t _Lrow_1, int32_t _Lcol_2);
void _Nglc_Pdecl_at_end_0();
void _Nglc_Pdecl_alias_4(_Nglc_Nid _Lname_0, _Nglc_Nat _Lat_1, int32_t _Lrow_2, int32_t _Lcol_3);
void _Nglc_Pat_push_4(_Nglc_Nid _Lname_0, _Nglc_Nname_type _Ltype_1, int32_t _Lrow_2, int32_t _Lcol_3);
_Nglc_Nat _Nglc_Pat_done_0();
void _Nglc_Pat_begin_0();
void _Nglc_Pat_begin_relative_0();
void _Nglc_Pat_begin_relative_pause_0();
void _Nglc_Pat_begin_relative_resume_0();
void _Nglc_Pat_root_0();
void _Nglc_Pat_alias_3(_Nglc_Nid _Lname_0, int32_t _Lrow_1, int32_t _Lcol_2);
void _Nglc_Pat_graves_3(int8_t _Lgraves_0, int32_t _Lrow_1, int32_t _Lcol_2);
_Nglc_Nat _Nglc_Pat_basic_type_1(_Nglc_Nbasic_type_id _Ltype_0);
void _Nglc_Pdecl_var_as_gvar_0();
void _Nglc_Ptype_info_arr_2(_Nglc_Nexpr_i* _Lexpr_v_0, uint8_t _Lexpr_c_1);
void _Nglc_Ptype_info_ref_1(int8_t _Lc_0);
void _Nglc_Ptype_info_static_0();
void _Nglc_Ptype_info_begin_0();
void _Nglc_Ptype_info_finalize_0();
_Nglc_Nexpr_i _Nglc_Pexpr_int_2(int32_t _Lvalue_0, _Nglc_Nexpr_int _Ltype_1);
_Nglc_Nexpr_i _Nglc_Pexpr_size_of_type_1(_Nglc_Nat _Lat_0);
_Nglc_Nexpr_i _Nglc_Pexpr_null_0();
void _Nglc_Pdecl_at_begin_enum_3(_Nglc_Nid _Lname_0, int32_t _Lrow_1, int32_t _Lcol_2);
void _Nglc_Pdecl_enum_end_3(_Nglc_Nat _Lbase_type_0, int32_t _Lrow_1, int32_t _Lcol_2);
_Nglc_Nexpr_i _Nglc_Pexpr_cvar_2(_Nglc_Nat _Lat_0, _Nglc_Nid _Lname_1);
void _Nglc_Penum_add_cvar_3(_Nglc_Nid _Lname_0, int32_t _Lrow_1, int32_t _Lcol_2);
void _Nglc_Pdecl_add_cvar_3(_Nglc_Nid _Lname_0, int32_t _Lrow_1, int32_t _Lcol_2);
void _Nglc_Penum_set_cvar_expr_1(_Nglc_Nexpr_i _Lset_0);
void _Nglc_Pstruct_attr_real_name_1(_Nglc_Nid _Lname_0);
void _Nglc_Pstruct_attr_union_0();
void _Nglc_Pstruct_attr_no_decl_0();
_Nglc_Nexpr_i _Nglc_Pexpr_str_1(_Nglc_Nexpr_i _Lprev_0);
_Nglc_Nexpr_i _Nglc_Pexpr_unary_2(_Nglc_Nexpr_i _Lexpr_0, _Nglc_Nunary _Ltype_1);
_Nglc_Nexpr_i _Nglc_Pexpr_ref_1(_Nglc_Nexpr_i _Lexpr_0);
_Nglc_Nexpr_i _Nglc_Pexpr_cast_fast_2(_Nglc_Nexpr_i _Lexpr_0, _Nglc_Nat _Ltype_1);
_Nglc_Nexpr_i _Nglc_Pexpr_index_3(_Nglc_Nexpr_i _Lleft_0, _Nglc_Nexpr_i* _Lright_v_1, int32_t _Lright_c_2);
void _Nglc_Penum_base_begin_0();
void _Nglc_Pstmt_switch_begin_0();
void _Nglc_Pstmt_switch_set_6(_Nglc_Nexpr_i _Lexpr_0, int32_t _Lbegin_row_1, int32_t _Lbegin_col_2, int32_t _Lend_row_3, int32_t _Lend_col_4, _Nglc_Nexpr_i _Lcases_5);
void _Nglc_Pstmt_switch_expr_add_1(_Nglc_Nexpr_i _Lexpr_0);
void _Nglc_Pstmt_switch_case_begin_5(int32_t _Lbegin_row_0, int32_t _Lbegin_col_1, int32_t _Lend_row_2, int32_t _Lend_col_3, bool _Lfall_through_4);
void _Nglc_Pstmt_switch_case_end_0();
void _Nglc_Pstmt_switch_default_begin_5(int32_t _Lbegin_row_0, int32_t _Lbegin_col_1, int32_t _Lend_row_2, int32_t _Lend_col_3, bool _Lfall_through_4);
void _Nglc_Pstmt_switch_default_end_0();
void _Nglc_Pstmt_switch_end_0();
void _Nglc_Pstmt_if_begin_0();
void _Nglc_Pstmt_if_set_6(bool _Lnot_0, _Nglc_Nexpr_i _Lexpr_1, int32_t _Lbegin_row_2, int32_t _Lbegin_col_3, int32_t _Lend_row_4, int32_t _Lend_col_5);
void _Nglc_Pstmt_if_end_0();
void _Nglc_Pstmt_do_begin_0();
void _Nglc_Pstmt_do_set_6(_Nglc_Nexpr_i _Lexpr_0, int32_t _Lbegin_row_1, int32_t _Lbegin_col_2, int32_t _Lend_row_3, int32_t _Lend_col_4, struct _Nglc_Nstmt_space* _Lcontinu_5);
void _Nglc_Pstmt_do_end_0();
void _Nglc_Pstmt_while_begin_0();
void _Nglc_Pstmt_while_set_6(_Nglc_Nexpr_i _Lexpr_0, int32_t _Lbegin_row_1, int32_t _Lbegin_col_2, int32_t _Lend_row_3, int32_t _Lend_col_4, struct _Nglc_Nstmt_space* _Lcontinu_5);
void _Nglc_Pstmt_while_end_0();
void _Nglc_Pstmt_elif_begin_0();
void _Nglc_Pstmt_elif_set_6(bool _Lnot_0, _Nglc_Nexpr_i _Lexpr_1, int32_t _Lbegin_row_2, int32_t _Lbegin_col_3, int32_t _Lend_row_4, int32_t _Lend_col_5);
void _Nglc_Pstmt_elif_end_0();
void _Nglc_Pstmt_else_set_0();
void _Nglc_Pstmt_else_end_0();
void _Nglc_Pstmt_if_end_ifs_0();
struct _Nglc_Nstmt_space* _Nglc_Pstmt_space_begin_0();
struct _Nglc_Nstmt_space* _Nglc_Pstmt_space_begin_detach_0();
struct _Nglc_Nstmt_space* _Nglc_Pstmt_space_end_0();
_Nglc_Nexpr_i _Nglc_Pexpr_compare_3(_Nglc_Nexpr_i _Lleft_0, _Nglc_Nexpr_i _Lright_1, _Nglc_Ncompare _Ltype_2);
_Nglc_Nexpr_i _Nglc_Pexpr_bool_1(bool _Lvalue_0);
_Nglc_Nexpr_i _Nglc_Pexpr_char_1(int32_t _Lvalue_0);
void _Nglc_Pcvar_attr_real_name_1(_Nglc_Nid _Lname_0);
void _Nglc_Pcvar_attr_no_decl_0();
